### ISSUE TITLE
Feature Request: isPullRequest

### ISSUE THREAD

**Issue by zixia** [watson/is-ci#16]
We need to identify whether one CI run is a Pull Request because the Environment Variables is not available with a Pull Request.

See: https://docs.travis-ci.com/user/pull-requests/#pull-requests-and-security-restrictions

**Comment by watson** [comment]
I think this is going to be tough to normalize across CI systems. Travis is easy because it's so tightly integrated with the GitHub workflow, but a lot of other CI systems approach this in a more generic way AFAIK. So I'm not really sure if this is feasible?

**Comment by Sibiraj-S** [comment]
Yes, also only few exposes the constants in the build Environment too

* TRAVIS_PULL_REQUEST (**boolean**)
* CIRCLE_PULL_REQUEST
* APPVEYOR_PULL_REQUEST_NUMBER
* BUILDKITE_PULL_REQUEST
* CIRRUS_PR
* CI_PULL_REQUEST (codeship - **boolean**)
* PULL_REQUEST_NUMBER (semaphore)
* IS_PULL_REQUEST (shippable - **boolean**)
* TDDIUM_PR_ID (solano)

**Comment by zixia** [comment]
Thank @watson for your reply, and thank @Sibiraj-S very much for your supported CI and environment variables list!

I think this feature will be very useful for us when we are using a CI that integrated with GitHub PR workflow.

As we had already listed the supported CI and environment variables, how about let's implement an `isPullRequest()` method, which can return `true`/`false` if we are sure this is(or not) a PR under CI, or throw an Exception if there's a CI that does not support to identify the PR, so that the user will know he can not use `isPullRequest` in their CI?

**Comment by watson** [comment]
Yes, thank you @Sibiraj-S for the great research. It's more commonly exposed than I feared.

I guess it doesn't hurt to expose this in some way with proper documentation about that it's not always supported.

I'm hesitant to throw an exception though 🤔 I'm thinking we instead could return `null` in the cases where it's not supported?

**Comment by watson** [comment]
@Sibiraj-S Oh yes, I was actually thinking to put this into ci-info. I forgot this issue was opened on the is-ci module. Then a is-pr module can depend on it just like is-ci is currently does.

**Comment by Sibiraj-S** [comment]
yes. then naming will also make perfect sense.

* ci-info
* is-ci
* is-pr

**Comment by watson** [comment]
@zixia The module [is-pr](https://github.com/watson/is-pr) have now been released to npm - please take it for a spin and let me know what you think 😃 

It has support for the CI servers @Sibiraj-S listed above, except Codeship.

The reason why Codeship isn't supported is because of this note I found when reading about its `CI_PULL_REQUEST` environment variable:

> _Note:_ The value of `CI_PULL_REQUEST` is `false`, and doesn’t indicate if a commit has a corresponding pull request, or if the build was triggered by a pull request. The variable exists because some third-party integrations require its existence.

**Comment by zixia** [comment]
Awesome，I'll try it out later.

Thank you for very much for creating those great modules!
