### ISSUE TITLE
Negative check is-not-ci?

### ISSUE THREAD

**Issue by Maxim-Mazurok** [watson/is-ci#22]
I want to run some script only if it's not in CI.

I've used this:
```json
{
    "is-not-ci": "npx -y --package \"is-ci\" --call \"node -e \\\"process.exit(require(\\\\\\\"is-ci\\\\\\\") ? 1 : 0)\\\"\"",
    "postinstall": "npm run is-not-ci && npm run blabla",
}
```

Is there any better option?

(needs to be cross-platform: Win and Linux)

**Comment by Maxim-Mazurok** [comment]
Turns out that doesn't work on CI though, because script returns exit code 1 and npm thinks that there's an error :(

**Comment by sibiraj-s** [comment]
just do

```
{
    "postinstall": "is-ci || npm run blabla",
}
```

**Comment by Maxim-Mazurok** [comment]
Indeed, that works. For some reason, I thought that `||` wasn't portable and wouldn't fly in `cmd.exe`... Thank you!
