### ISSUE TITLE
Add support for Ionic AppFlow

### ISSUE THREAD

**Issue by nelson6e65** [watson/is-ci#25]
https://ionic.io/docs/appflow/automation/environments#predefined-environments

**Comment by sibiraj-s** [comment]
Thanks. Closing this since it is tracked under https://github.com/watson/ci-info/issues/79. ci-info has semver minor. so a ci-info package update would be enough.

https://github.com/watson/is-ci/blob/6bae6da07ef8dc03f9cb0f6cd9fb1db0393ecd22/package.json#L31-L32
